//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS_MAT_MVC.ProxyCarrera {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CarreraDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Matriculas")]
    [System.SerializableAttribute()]
    public partial class CarreraDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_carreraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_carreraField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_carrera {
            get {
                return this.Id_carreraField;
            }
            set {
                if ((this.Id_carreraField.Equals(value) != true)) {
                    this.Id_carreraField = value;
                    this.RaisePropertyChanged("Id_carrera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_carrera {
            get {
                return this.Nom_carreraField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_carreraField, value) != true)) {
                    this.Nom_carreraField = value;
                    this.RaisePropertyChanged("Nom_carrera");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyCarrera.IServicioCarrera")]
    public interface IServicioCarrera {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCarrera/ListarCarrera", ReplyAction="http://tempuri.org/IServicioCarrera/ListarCarreraResponse")]
        SIS_MAT_MVC.ProxyCarrera.CarreraDC[] ListarCarrera();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioCarrera/ListarCarrera", ReplyAction="http://tempuri.org/IServicioCarrera/ListarCarreraResponse")]
        System.Threading.Tasks.Task<SIS_MAT_MVC.ProxyCarrera.CarreraDC[]> ListarCarreraAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioCarreraChannel : SIS_MAT_MVC.ProxyCarrera.IServicioCarrera, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioCarreraClient : System.ServiceModel.ClientBase<SIS_MAT_MVC.ProxyCarrera.IServicioCarrera>, SIS_MAT_MVC.ProxyCarrera.IServicioCarrera {
        
        public ServicioCarreraClient() {
        }
        
        public ServicioCarreraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioCarreraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCarreraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioCarreraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SIS_MAT_MVC.ProxyCarrera.CarreraDC[] ListarCarrera() {
            return base.Channel.ListarCarrera();
        }
        
        public System.Threading.Tasks.Task<SIS_MAT_MVC.ProxyCarrera.CarreraDC[]> ListarCarreraAsync() {
            return base.Channel.ListarCarreraAsync();
        }
    }
}
