//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Matriculas
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SISTEMA_MATRICULASEntities : DbContext
    {
        public SISTEMA_MATRICULASEntities()
            : base("name=SISTEMA_MATRICULASEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tb_ALUMNO> Tb_ALUMNO { get; set; }
        public virtual DbSet<Tb_DETMATRICULA> Tb_DETMATRICULA { get; set; }
        public virtual DbSet<Tb_MATRICULA> Tb_MATRICULA { get; set; }
        public virtual DbSet<Tb_PROFESOR> Tb_PROFESOR { get; set; }
        public virtual DbSet<Tb_Ubigeo> Tb_Ubigeo { get; set; }
        public virtual DbSet<Tb_CUOTA> Tb_CUOTA { get; set; }
        public virtual DbSet<Tb_CURSO> Tb_CURSO { get; set; }
        public virtual DbSet<vw_VistaAlumnos> vw_VistaAlumnos { get; set; }
        public virtual DbSet<vw_VistaProfesores> vw_VistaProfesores { get; set; }
        public virtual DbSet<vw_VistaCuotas> vw_VistaCuotas { get; set; }
        public virtual DbSet<vw_VistaCursos> vw_VistaCursos { get; set; }
    
        public virtual int usp_delete_alumno(Nullable<int> id_alumno)
        {
            var id_alumnoParameter = id_alumno.HasValue ?
                new ObjectParameter("id_alumno", id_alumno) :
                new ObjectParameter("id_alumno", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_delete_alumno", id_alumnoParameter);
        }
    
        public virtual int usp_insert_alumno(string id_Ubigeo, string dni_alum, byte[] foto_alum, Nullable<System.DateTime> fec_nac, string sexo, string nom_alum, string ape_alum, string dir_alum, string tel_alum, string email_alum, string usu_Registro, Nullable<int> est_alum)
        {
            var id_UbigeoParameter = id_Ubigeo != null ?
                new ObjectParameter("Id_Ubigeo", id_Ubigeo) :
                new ObjectParameter("Id_Ubigeo", typeof(string));
    
            var dni_alumParameter = dni_alum != null ?
                new ObjectParameter("Dni_alum", dni_alum) :
                new ObjectParameter("Dni_alum", typeof(string));
    
            var foto_alumParameter = foto_alum != null ?
                new ObjectParameter("Foto_alum", foto_alum) :
                new ObjectParameter("Foto_alum", typeof(byte[]));
    
            var fec_nacParameter = fec_nac.HasValue ?
                new ObjectParameter("Fec_nac", fec_nac) :
                new ObjectParameter("Fec_nac", typeof(System.DateTime));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(string));
    
            var nom_alumParameter = nom_alum != null ?
                new ObjectParameter("Nom_alum", nom_alum) :
                new ObjectParameter("Nom_alum", typeof(string));
    
            var ape_alumParameter = ape_alum != null ?
                new ObjectParameter("Ape_alum", ape_alum) :
                new ObjectParameter("Ape_alum", typeof(string));
    
            var dir_alumParameter = dir_alum != null ?
                new ObjectParameter("Dir_alum", dir_alum) :
                new ObjectParameter("Dir_alum", typeof(string));
    
            var tel_alumParameter = tel_alum != null ?
                new ObjectParameter("Tel_alum", tel_alum) :
                new ObjectParameter("Tel_alum", typeof(string));
    
            var email_alumParameter = email_alum != null ?
                new ObjectParameter("Email_alum", email_alum) :
                new ObjectParameter("Email_alum", typeof(string));
    
            var usu_RegistroParameter = usu_Registro != null ?
                new ObjectParameter("Usu_Registro", usu_Registro) :
                new ObjectParameter("Usu_Registro", typeof(string));
    
            var est_alumParameter = est_alum.HasValue ?
                new ObjectParameter("Est_alum", est_alum) :
                new ObjectParameter("Est_alum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insert_alumno", id_UbigeoParameter, dni_alumParameter, foto_alumParameter, fec_nacParameter, sexoParameter, nom_alumParameter, ape_alumParameter, dir_alumParameter, tel_alumParameter, email_alumParameter, usu_RegistroParameter, est_alumParameter);
        }
    
        public virtual int usp_update_alumno(Nullable<int> id_alumno, string id_Ubigeo, string dni_alum, byte[] foto_alum, Nullable<System.DateTime> fec_nac, string sexo, string nom_alum, string ape_alum, string dir_alum, string tel_alum, string email_alum, string usu_Ult_Mod, Nullable<int> est_alum)
        {
            var id_alumnoParameter = id_alumno.HasValue ?
                new ObjectParameter("id_alumno", id_alumno) :
                new ObjectParameter("id_alumno", typeof(int));
    
            var id_UbigeoParameter = id_Ubigeo != null ?
                new ObjectParameter("Id_Ubigeo", id_Ubigeo) :
                new ObjectParameter("Id_Ubigeo", typeof(string));
    
            var dni_alumParameter = dni_alum != null ?
                new ObjectParameter("Dni_alum", dni_alum) :
                new ObjectParameter("Dni_alum", typeof(string));
    
            var foto_alumParameter = foto_alum != null ?
                new ObjectParameter("Foto_alum", foto_alum) :
                new ObjectParameter("Foto_alum", typeof(byte[]));
    
            var fec_nacParameter = fec_nac.HasValue ?
                new ObjectParameter("Fec_nac", fec_nac) :
                new ObjectParameter("Fec_nac", typeof(System.DateTime));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(string));
    
            var nom_alumParameter = nom_alum != null ?
                new ObjectParameter("Nom_alum", nom_alum) :
                new ObjectParameter("Nom_alum", typeof(string));
    
            var ape_alumParameter = ape_alum != null ?
                new ObjectParameter("Ape_alum", ape_alum) :
                new ObjectParameter("Ape_alum", typeof(string));
    
            var dir_alumParameter = dir_alum != null ?
                new ObjectParameter("Dir_alum", dir_alum) :
                new ObjectParameter("Dir_alum", typeof(string));
    
            var tel_alumParameter = tel_alum != null ?
                new ObjectParameter("Tel_alum", tel_alum) :
                new ObjectParameter("Tel_alum", typeof(string));
    
            var email_alumParameter = email_alum != null ?
                new ObjectParameter("Email_alum", email_alum) :
                new ObjectParameter("Email_alum", typeof(string));
    
            var usu_Ult_ModParameter = usu_Ult_Mod != null ?
                new ObjectParameter("Usu_Ult_Mod", usu_Ult_Mod) :
                new ObjectParameter("Usu_Ult_Mod", typeof(string));
    
            var est_alumParameter = est_alum.HasValue ?
                new ObjectParameter("Est_alum", est_alum) :
                new ObjectParameter("Est_alum", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_update_alumno", id_alumnoParameter, id_UbigeoParameter, dni_alumParameter, foto_alumParameter, fec_nacParameter, sexoParameter, nom_alumParameter, ape_alumParameter, dir_alumParameter, tel_alumParameter, email_alumParameter, usu_Ult_ModParameter, est_alumParameter);
        }
    
        public virtual ObjectResult<usp_consultar_cuota_Result> usp_consultar_cuota(Nullable<int> id_cuota)
        {
            var id_cuotaParameter = id_cuota.HasValue ?
                new ObjectParameter("id_cuota", id_cuota) :
                new ObjectParameter("id_cuota", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_consultar_cuota_Result>("usp_consultar_cuota", id_cuotaParameter);
        }
    
        public virtual int usp_delete_cuota(Nullable<int> id_cuota)
        {
            var id_cuotaParameter = id_cuota.HasValue ?
                new ObjectParameter("id_cuota", id_cuota) :
                new ObjectParameter("id_cuota", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_delete_cuota", id_cuotaParameter);
        }
    
        public virtual int usp_insert_cuota(Nullable<int> id_alum, string ndoc_cuota, Nullable<System.DateTime> fecha_pago, Nullable<int> est_cuota, Nullable<int> tip_cuota, Nullable<System.DateTime> vencimiento, Nullable<decimal> precio_cuota)
        {
            var id_alumParameter = id_alum.HasValue ?
                new ObjectParameter("Id_alum", id_alum) :
                new ObjectParameter("Id_alum", typeof(int));
    
            var ndoc_cuotaParameter = ndoc_cuota != null ?
                new ObjectParameter("Ndoc_cuota", ndoc_cuota) :
                new ObjectParameter("Ndoc_cuota", typeof(string));
    
            var fecha_pagoParameter = fecha_pago.HasValue ?
                new ObjectParameter("Fecha_pago", fecha_pago) :
                new ObjectParameter("Fecha_pago", typeof(System.DateTime));
    
            var est_cuotaParameter = est_cuota.HasValue ?
                new ObjectParameter("Est_cuota", est_cuota) :
                new ObjectParameter("Est_cuota", typeof(int));
    
            var tip_cuotaParameter = tip_cuota.HasValue ?
                new ObjectParameter("Tip_cuota", tip_cuota) :
                new ObjectParameter("Tip_cuota", typeof(int));
    
            var vencimientoParameter = vencimiento.HasValue ?
                new ObjectParameter("Vencimiento", vencimiento) :
                new ObjectParameter("Vencimiento", typeof(System.DateTime));
    
            var precio_cuotaParameter = precio_cuota.HasValue ?
                new ObjectParameter("Precio_cuota", precio_cuota) :
                new ObjectParameter("Precio_cuota", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insert_cuota", id_alumParameter, ndoc_cuotaParameter, fecha_pagoParameter, est_cuotaParameter, tip_cuotaParameter, vencimientoParameter, precio_cuotaParameter);
        }
    
        public virtual ObjectResult<usp_listar_cuota_Result> usp_listar_cuota()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_listar_cuota_Result>("usp_listar_cuota");
        }
    
        public virtual int usp_update_cuota(Nullable<int> id_cuota, Nullable<int> id_alum, string ndoc_cuota, Nullable<System.DateTime> fecha_pago, Nullable<int> est_cuota, Nullable<int> tip_cuota, Nullable<System.DateTime> vencimiento, Nullable<decimal> precio_cuota)
        {
            var id_cuotaParameter = id_cuota.HasValue ?
                new ObjectParameter("Id_cuota", id_cuota) :
                new ObjectParameter("Id_cuota", typeof(int));
    
            var id_alumParameter = id_alum.HasValue ?
                new ObjectParameter("Id_alum", id_alum) :
                new ObjectParameter("Id_alum", typeof(int));
    
            var ndoc_cuotaParameter = ndoc_cuota != null ?
                new ObjectParameter("Ndoc_cuota", ndoc_cuota) :
                new ObjectParameter("Ndoc_cuota", typeof(string));
    
            var fecha_pagoParameter = fecha_pago.HasValue ?
                new ObjectParameter("Fecha_pago", fecha_pago) :
                new ObjectParameter("Fecha_pago", typeof(System.DateTime));
    
            var est_cuotaParameter = est_cuota.HasValue ?
                new ObjectParameter("Est_cuota", est_cuota) :
                new ObjectParameter("Est_cuota", typeof(int));
    
            var tip_cuotaParameter = tip_cuota.HasValue ?
                new ObjectParameter("Tip_cuota", tip_cuota) :
                new ObjectParameter("Tip_cuota", typeof(int));
    
            var vencimientoParameter = vencimiento.HasValue ?
                new ObjectParameter("Vencimiento", vencimiento) :
                new ObjectParameter("Vencimiento", typeof(System.DateTime));
    
            var precio_cuotaParameter = precio_cuota.HasValue ?
                new ObjectParameter("Precio_cuota", precio_cuota) :
                new ObjectParameter("Precio_cuota", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_update_cuota", id_cuotaParameter, id_alumParameter, ndoc_cuotaParameter, fecha_pagoParameter, est_cuotaParameter, tip_cuotaParameter, vencimientoParameter, precio_cuotaParameter);
        }
    
        public virtual int usp_delete_profesor(Nullable<int> id_profe)
        {
            var id_profeParameter = id_profe.HasValue ?
                new ObjectParameter("id_profe", id_profe) :
                new ObjectParameter("id_profe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_delete_profesor", id_profeParameter);
        }
    
        public virtual int usp_insert_profesor(string id_Ubigeo, Nullable<int> id_esp, string sexo, byte[] foto_profe, string dni_profe, string nom_profe, string ape_profe, string tel_profe, string email_profe, string usu_Registro, Nullable<int> est_prof)
        {
            var id_UbigeoParameter = id_Ubigeo != null ?
                new ObjectParameter("Id_Ubigeo", id_Ubigeo) :
                new ObjectParameter("Id_Ubigeo", typeof(string));
    
            var id_espParameter = id_esp.HasValue ?
                new ObjectParameter("Id_esp", id_esp) :
                new ObjectParameter("Id_esp", typeof(int));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(string));
    
            var foto_profeParameter = foto_profe != null ?
                new ObjectParameter("Foto_profe", foto_profe) :
                new ObjectParameter("Foto_profe", typeof(byte[]));
    
            var dni_profeParameter = dni_profe != null ?
                new ObjectParameter("Dni_profe", dni_profe) :
                new ObjectParameter("Dni_profe", typeof(string));
    
            var nom_profeParameter = nom_profe != null ?
                new ObjectParameter("Nom_profe", nom_profe) :
                new ObjectParameter("Nom_profe", typeof(string));
    
            var ape_profeParameter = ape_profe != null ?
                new ObjectParameter("Ape_profe", ape_profe) :
                new ObjectParameter("Ape_profe", typeof(string));
    
            var tel_profeParameter = tel_profe != null ?
                new ObjectParameter("Tel_profe", tel_profe) :
                new ObjectParameter("Tel_profe", typeof(string));
    
            var email_profeParameter = email_profe != null ?
                new ObjectParameter("Email_profe", email_profe) :
                new ObjectParameter("Email_profe", typeof(string));
    
            var usu_RegistroParameter = usu_Registro != null ?
                new ObjectParameter("Usu_Registro", usu_Registro) :
                new ObjectParameter("Usu_Registro", typeof(string));
    
            var est_profParameter = est_prof.HasValue ?
                new ObjectParameter("Est_prof", est_prof) :
                new ObjectParameter("Est_prof", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insert_profesor", id_UbigeoParameter, id_espParameter, sexoParameter, foto_profeParameter, dni_profeParameter, nom_profeParameter, ape_profeParameter, tel_profeParameter, email_profeParameter, usu_RegistroParameter, est_profParameter);
        }
    
        public virtual int usp_update_profesor(Nullable<int> id_profe, string id_Ubigeo, Nullable<int> id_esp, string sexo, byte[] foto_profe, string dni_profe, string nom_profe, string ape_profe, string tel_profe, string email_profe, string usu_Ult_Mod, Nullable<int> est_prof)
        {
            var id_profeParameter = id_profe.HasValue ?
                new ObjectParameter("id_profe", id_profe) :
                new ObjectParameter("id_profe", typeof(int));
    
            var id_UbigeoParameter = id_Ubigeo != null ?
                new ObjectParameter("Id_Ubigeo", id_Ubigeo) :
                new ObjectParameter("Id_Ubigeo", typeof(string));
    
            var id_espParameter = id_esp.HasValue ?
                new ObjectParameter("Id_esp", id_esp) :
                new ObjectParameter("Id_esp", typeof(int));
    
            var sexoParameter = sexo != null ?
                new ObjectParameter("Sexo", sexo) :
                new ObjectParameter("Sexo", typeof(string));
    
            var foto_profeParameter = foto_profe != null ?
                new ObjectParameter("Foto_profe", foto_profe) :
                new ObjectParameter("Foto_profe", typeof(byte[]));
    
            var dni_profeParameter = dni_profe != null ?
                new ObjectParameter("Dni_profe", dni_profe) :
                new ObjectParameter("Dni_profe", typeof(string));
    
            var nom_profeParameter = nom_profe != null ?
                new ObjectParameter("Nom_profe", nom_profe) :
                new ObjectParameter("Nom_profe", typeof(string));
    
            var ape_profeParameter = ape_profe != null ?
                new ObjectParameter("Ape_profe", ape_profe) :
                new ObjectParameter("Ape_profe", typeof(string));
    
            var tel_profeParameter = tel_profe != null ?
                new ObjectParameter("Tel_profe", tel_profe) :
                new ObjectParameter("Tel_profe", typeof(string));
    
            var email_profeParameter = email_profe != null ?
                new ObjectParameter("Email_profe", email_profe) :
                new ObjectParameter("Email_profe", typeof(string));
    
            var usu_Ult_ModParameter = usu_Ult_Mod != null ?
                new ObjectParameter("Usu_Ult_Mod", usu_Ult_Mod) :
                new ObjectParameter("Usu_Ult_Mod", typeof(string));
    
            var est_profParameter = est_prof.HasValue ?
                new ObjectParameter("Est_prof", est_prof) :
                new ObjectParameter("Est_prof", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_update_profesor", id_profeParameter, id_UbigeoParameter, id_espParameter, sexoParameter, foto_profeParameter, dni_profeParameter, nom_profeParameter, ape_profeParameter, tel_profeParameter, email_profeParameter, usu_Ult_ModParameter, est_profParameter);
        }
    
        public virtual ObjectResult<usp_ConsultarMatriculadosEntreFechas_Result> usp_ConsultarMatriculadosEntreFechas(Nullable<System.DateTime> fechaInicio, Nullable<System.DateTime> fechaFin)
        {
            var fechaInicioParameter = fechaInicio.HasValue ?
                new ObjectParameter("fechaInicio", fechaInicio) :
                new ObjectParameter("fechaInicio", typeof(System.DateTime));
    
            var fechaFinParameter = fechaFin.HasValue ?
                new ObjectParameter("fechaFin", fechaFin) :
                new ObjectParameter("fechaFin", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ConsultarMatriculadosEntreFechas_Result>("usp_ConsultarMatriculadosEntreFechas", fechaInicioParameter, fechaFinParameter);
        }
    
        public virtual ObjectResult<usp_ListarAlumnosCarrera_Result> usp_ListarAlumnosCarrera(Nullable<int> id_carrera)
        {
            var id_carreraParameter = id_carrera.HasValue ?
                new ObjectParameter("Id_carrera", id_carrera) :
                new ObjectParameter("Id_carrera", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarAlumnosCarrera_Result>("usp_ListarAlumnosCarrera", id_carreraParameter);
        }
    
        public virtual ObjectResult<usp_ListarBloquesVacantes_Result> usp_ListarBloquesVacantes(Nullable<short> vacantes)
        {
            var vacantesParameter = vacantes.HasValue ?
                new ObjectParameter("vacantes", vacantes) :
                new ObjectParameter("vacantes", typeof(short));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_ListarBloquesVacantes_Result>("usp_ListarBloquesVacantes", vacantesParameter);
        }
    
        public virtual ObjectResult<usp_consultar_cursos_Result> usp_consultar_cursos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_consultar_cursos_Result>("usp_consultar_cursos");
        }
    
        public virtual int usp_delete_curso(Nullable<int> id_curso)
        {
            var id_cursoParameter = id_curso.HasValue ?
                new ObjectParameter("Id_curso", id_curso) :
                new ObjectParameter("Id_curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_delete_curso", id_cursoParameter);
        }
    
        public virtual int usp_insert_curso(string des_curso, string usu_Registro, Nullable<System.DateTime> fec_reg, Nullable<int> est_curso)
        {
            var des_cursoParameter = des_curso != null ?
                new ObjectParameter("Des_curso", des_curso) :
                new ObjectParameter("Des_curso", typeof(string));
    
            var usu_RegistroParameter = usu_Registro != null ?
                new ObjectParameter("Usu_Registro", usu_Registro) :
                new ObjectParameter("Usu_Registro", typeof(string));
    
            var fec_regParameter = fec_reg.HasValue ?
                new ObjectParameter("Fec_reg", fec_reg) :
                new ObjectParameter("Fec_reg", typeof(System.DateTime));
    
            var est_cursoParameter = est_curso.HasValue ?
                new ObjectParameter("Est_curso", est_curso) :
                new ObjectParameter("Est_curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_insert_curso", des_cursoParameter, usu_RegistroParameter, fec_regParameter, est_cursoParameter);
        }
    
        public virtual int usp_update_curso(Nullable<int> id_curso, string des_curso, string usu_Ult_Mod, Nullable<System.DateTime> fec_Ult_Mod, Nullable<int> est_curso)
        {
            var id_cursoParameter = id_curso.HasValue ?
                new ObjectParameter("Id_curso", id_curso) :
                new ObjectParameter("Id_curso", typeof(int));
    
            var des_cursoParameter = des_curso != null ?
                new ObjectParameter("Des_curso", des_curso) :
                new ObjectParameter("Des_curso", typeof(string));
    
            var usu_Ult_ModParameter = usu_Ult_Mod != null ?
                new ObjectParameter("Usu_Ult_Mod", usu_Ult_Mod) :
                new ObjectParameter("Usu_Ult_Mod", typeof(string));
    
            var fec_Ult_ModParameter = fec_Ult_Mod.HasValue ?
                new ObjectParameter("Fec_Ult_Mod", fec_Ult_Mod) :
                new ObjectParameter("Fec_Ult_Mod", typeof(System.DateTime));
    
            var est_cursoParameter = est_curso.HasValue ?
                new ObjectParameter("Est_curso", est_curso) :
                new ObjectParameter("Est_curso", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("usp_update_curso", id_cursoParameter, des_cursoParameter, usu_Ult_ModParameter, fec_Ult_ModParameter, est_cursoParameter);
        }
    }
}
