
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WCF_Matriculas
{

using System;
    using System.Collections.Generic;
    
public partial class Tb_DETMATRICULA
{

    public int Id_matricula { get; set; }

    public string Id_bloque { get; set; }



    public virtual Tb_MATRICULA Tb_MATRICULA { get; set; }

}

}
