
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WCF_Matriculas
{

using System;
    using System.Collections.Generic;
    
public partial class Tb_ESPECIALIDAD
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tb_ESPECIALIDAD()
    {

        this.Tb_PROFESOR = new HashSet<Tb_PROFESOR>();

    }


    public int Id_esp { get; set; }

    public string Des_esp { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tb_PROFESOR> Tb_PROFESOR { get; set; }

}

}
