
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WCF_Matriculas
{

using System;
    using System.Collections.Generic;
    
public partial class Tb_MATRICULA
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public Tb_MATRICULA()
    {

        this.Tb_DETMATRICULA = new HashSet<Tb_DETMATRICULA>();

    }


    public int Id_matricula { get; set; }

    public int Id_semestre { get; set; }

    public int Id_carrera { get; set; }

    public int Id_alum { get; set; }

    public string Usu_Registro { get; set; }

    public System.DateTime Fec_reg { get; set; }

    public string Usu_Ult_Mod { get; set; }

    public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }

    public Nullable<int> Est_matricula { get; set; }



    public virtual Tb_ALUMNO Tb_ALUMNO { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<Tb_DETMATRICULA> Tb_DETMATRICULA { get; set; }

}

}
