
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WCF_Matriculas
{

using System;
    using System.Collections.Generic;
    
public partial class vw_VistaCuotas
{

    public int Id_cuota { get; set; }

    public int Id_alum { get; set; }

    public string NombreCompleto { get; set; }

    public string Ndoc_cuota { get; set; }

    public Nullable<System.DateTime> Fecha_pago { get; set; }

    public int Est_cuota { get; set; }

    public string EstadoCuota { get; set; }

    public int Tip_cuota { get; set; }

    public string TipoCuota { get; set; }

    public Nullable<System.DateTime> Vencimiento { get; set; }

    public Nullable<decimal> Precio_cuota { get; set; }

}

}
