//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Matriculas
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_VistaProfesores
    {
        public int Id_profe { get; set; }
        public string Id_Ubigeo { get; set; }
        public string Nom_profe { get; set; }
        public string Ape_profe { get; set; }
        public string Sexo { get; set; }
        public int Id_esp { get; set; }
        public string Des_esp { get; set; }
        public byte[] Foto_profe { get; set; }
        public string Dni_profe { get; set; }
        public string Tel_profe { get; set; }
        public string Email_profe { get; set; }
        public Nullable<System.DateTime> Fec_reg { get; set; }
        public string Usu_Registro { get; set; }
        public Nullable<System.DateTime> Fec_Ult_Mod { get; set; }
        public string Usu_Ult_Mod { get; set; }
        public int Est_prof { get; set; }
        public string Estado { get; set; }
        public string Departamento { get; set; }
        public string Provincia { get; set; }
        public string Distrito { get; set; }
    }
}
