//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente_WCF_Matriculas.ProxyProfesor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfesorDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Matriculas")]
    [System.SerializableAttribute()]
    public partial class ProfesorDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_profeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Des_espField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dni_profeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Email_profeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_regField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_UbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_espField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_profeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_profeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tel_profeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_profe {
            get {
                return this.Ape_profeField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_profeField, value) != true)) {
                    this.Ape_profeField = value;
                    this.RaisePropertyChanged("Ape_profe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Des_esp {
            get {
                return this.Des_espField;
            }
            set {
                if ((object.ReferenceEquals(this.Des_espField, value) != true)) {
                    this.Des_espField = value;
                    this.RaisePropertyChanged("Des_esp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni_profe {
            get {
                return this.Dni_profeField;
            }
            set {
                if ((object.ReferenceEquals(this.Dni_profeField, value) != true)) {
                    this.Dni_profeField = value;
                    this.RaisePropertyChanged("Dni_profe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email_profe {
            get {
                return this.Email_profeField;
            }
            set {
                if ((object.ReferenceEquals(this.Email_profeField, value) != true)) {
                    this.Email_profeField = value;
                    this.RaisePropertyChanged("Email_profe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod {
            get {
                return this.Fec_Ult_ModField;
            }
            set {
                if ((this.Fec_Ult_ModField.Equals(value) != true)) {
                    this.Fec_Ult_ModField = value;
                    this.RaisePropertyChanged("Fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_reg {
            get {
                return this.Fec_regField;
            }
            set {
                if ((this.Fec_regField.Equals(value) != true)) {
                    this.Fec_regField = value;
                    this.RaisePropertyChanged("Fec_reg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubigeo {
            get {
                return this.Id_UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_UbigeoField, value) != true)) {
                    this.Id_UbigeoField = value;
                    this.RaisePropertyChanged("Id_Ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_esp {
            get {
                return this.Id_espField;
            }
            set {
                if ((this.Id_espField.Equals(value) != true)) {
                    this.Id_espField = value;
                    this.RaisePropertyChanged("Id_esp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_profe {
            get {
                return this.Id_profeField;
            }
            set {
                if ((this.Id_profeField.Equals(value) != true)) {
                    this.Id_profeField = value;
                    this.RaisePropertyChanged("Id_profe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_profe {
            get {
                return this.Nom_profeField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_profeField, value) != true)) {
                    this.Nom_profeField = value;
                    this.RaisePropertyChanged("Nom_profe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel_profe {
            get {
                return this.Tel_profeField;
            }
            set {
                if ((object.ReferenceEquals(this.Tel_profeField, value) != true)) {
                    this.Tel_profeField = value;
                    this.RaisePropertyChanged("Tel_profe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfesorDCINSERTS", Namespace="http://schemas.datacontract.org/2004/07/WCF_Matriculas")]
    [System.SerializableAttribute()]
    public partial class ProfesorDCINSERTS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_profeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dni_profeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Email_profeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Est_profField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_UbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_espField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_profeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tel_profeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_profe {
            get {
                return this.Ape_profeField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_profeField, value) != true)) {
                    this.Ape_profeField = value;
                    this.RaisePropertyChanged("Ape_profe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni_profe {
            get {
                return this.Dni_profeField;
            }
            set {
                if ((object.ReferenceEquals(this.Dni_profeField, value) != true)) {
                    this.Dni_profeField = value;
                    this.RaisePropertyChanged("Dni_profe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email_profe {
            get {
                return this.Email_profeField;
            }
            set {
                if ((object.ReferenceEquals(this.Email_profeField, value) != true)) {
                    this.Email_profeField = value;
                    this.RaisePropertyChanged("Email_profe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Est_prof {
            get {
                return this.Est_profField;
            }
            set {
                if ((this.Est_profField.Equals(value) != true)) {
                    this.Est_profField = value;
                    this.RaisePropertyChanged("Est_prof");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubigeo {
            get {
                return this.Id_UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_UbigeoField, value) != true)) {
                    this.Id_UbigeoField = value;
                    this.RaisePropertyChanged("Id_Ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_esp {
            get {
                return this.Id_espField;
            }
            set {
                if ((this.Id_espField.Equals(value) != true)) {
                    this.Id_espField = value;
                    this.RaisePropertyChanged("Id_esp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_profe {
            get {
                return this.Nom_profeField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_profeField, value) != true)) {
                    this.Nom_profeField = value;
                    this.RaisePropertyChanged("Nom_profe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel_profe {
            get {
                return this.Tel_profeField;
            }
            set {
                if ((object.ReferenceEquals(this.Tel_profeField, value) != true)) {
                    this.Tel_profeField = value;
                    this.RaisePropertyChanged("Tel_profe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProfesorDCUPDATES", Namespace="http://schemas.datacontract.org/2004/07/WCF_Matriculas")]
    [System.SerializableAttribute()]
    public partial class ProfesorDCUPDATES : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_profeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dni_profeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Email_profeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Est_profField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_UbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_espField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_profeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_profeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tel_profeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_profe {
            get {
                return this.Ape_profeField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_profeField, value) != true)) {
                    this.Ape_profeField = value;
                    this.RaisePropertyChanged("Ape_profe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni_profe {
            get {
                return this.Dni_profeField;
            }
            set {
                if ((object.ReferenceEquals(this.Dni_profeField, value) != true)) {
                    this.Dni_profeField = value;
                    this.RaisePropertyChanged("Dni_profe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email_profe {
            get {
                return this.Email_profeField;
            }
            set {
                if ((object.ReferenceEquals(this.Email_profeField, value) != true)) {
                    this.Email_profeField = value;
                    this.RaisePropertyChanged("Email_profe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Est_prof {
            get {
                return this.Est_profField;
            }
            set {
                if ((this.Est_profField.Equals(value) != true)) {
                    this.Est_profField = value;
                    this.RaisePropertyChanged("Est_prof");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubigeo {
            get {
                return this.Id_UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_UbigeoField, value) != true)) {
                    this.Id_UbigeoField = value;
                    this.RaisePropertyChanged("Id_Ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_esp {
            get {
                return this.Id_espField;
            }
            set {
                if ((this.Id_espField.Equals(value) != true)) {
                    this.Id_espField = value;
                    this.RaisePropertyChanged("Id_esp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_profe {
            get {
                return this.Id_profeField;
            }
            set {
                if ((this.Id_profeField.Equals(value) != true)) {
                    this.Id_profeField = value;
                    this.RaisePropertyChanged("Id_profe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_profe {
            get {
                return this.Nom_profeField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_profeField, value) != true)) {
                    this.Nom_profeField = value;
                    this.RaisePropertyChanged("Nom_profe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel_profe {
            get {
                return this.Tel_profeField;
            }
            set {
                if ((object.ReferenceEquals(this.Tel_profeField, value) != true)) {
                    this.Tel_profeField = value;
                    this.RaisePropertyChanged("Tel_profe");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyProfesor.IServicioProfesor")]
    public interface IServicioProfesor {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ConsultarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ConsultarProfesorResponse")]
        Cliente_WCF_Matriculas.ProxyProfesor.ProfesorDC ConsultarProfesor(int idProfe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ConsultarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ConsultarProfesorResponse")]
        System.Threading.Tasks.Task<Cliente_WCF_Matriculas.ProxyProfesor.ProfesorDC> ConsultarProfesorAsync(int idProfe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ListarProfesores", ReplyAction="http://tempuri.org/IServicioProfesor/ListarProfesoresResponse")]
        Cliente_WCF_Matriculas.ProxyProfesor.ProfesorDC[] ListarProfesores();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ListarProfesores", ReplyAction="http://tempuri.org/IServicioProfesor/ListarProfesoresResponse")]
        System.Threading.Tasks.Task<Cliente_WCF_Matriculas.ProxyProfesor.ProfesorDC[]> ListarProfesoresAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/EliminarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/EliminarProfesorResponse")]
        bool EliminarProfesor(int idProfe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/EliminarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/EliminarProfesorResponse")]
        System.Threading.Tasks.Task<bool> EliminarProfesorAsync(int idProfe);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/InsertarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/InsertarProfesorResponse")]
        bool InsertarProfesor(Cliente_WCF_Matriculas.ProxyProfesor.ProfesorDCINSERTS objProfesorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/InsertarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/InsertarProfesorResponse")]
        System.Threading.Tasks.Task<bool> InsertarProfesorAsync(Cliente_WCF_Matriculas.ProxyProfesor.ProfesorDCINSERTS objProfesorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ActualizarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ActualizarProfesorResponse")]
        bool ActualizarProfesor(Cliente_WCF_Matriculas.ProxyProfesor.ProfesorDCUPDATES objProfesorDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioProfesor/ActualizarProfesor", ReplyAction="http://tempuri.org/IServicioProfesor/ActualizarProfesorResponse")]
        System.Threading.Tasks.Task<bool> ActualizarProfesorAsync(Cliente_WCF_Matriculas.ProxyProfesor.ProfesorDCUPDATES objProfesorDC);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioProfesorChannel : Cliente_WCF_Matriculas.ProxyProfesor.IServicioProfesor, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioProfesorClient : System.ServiceModel.ClientBase<Cliente_WCF_Matriculas.ProxyProfesor.IServicioProfesor>, Cliente_WCF_Matriculas.ProxyProfesor.IServicioProfesor {
        
        public ServicioProfesorClient() {
        }
        
        public ServicioProfesorClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioProfesorClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProfesorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioProfesorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Cliente_WCF_Matriculas.ProxyProfesor.ProfesorDC ConsultarProfesor(int idProfe) {
            return base.Channel.ConsultarProfesor(idProfe);
        }
        
        public System.Threading.Tasks.Task<Cliente_WCF_Matriculas.ProxyProfesor.ProfesorDC> ConsultarProfesorAsync(int idProfe) {
            return base.Channel.ConsultarProfesorAsync(idProfe);
        }
        
        public Cliente_WCF_Matriculas.ProxyProfesor.ProfesorDC[] ListarProfesores() {
            return base.Channel.ListarProfesores();
        }
        
        public System.Threading.Tasks.Task<Cliente_WCF_Matriculas.ProxyProfesor.ProfesorDC[]> ListarProfesoresAsync() {
            return base.Channel.ListarProfesoresAsync();
        }
        
        public bool EliminarProfesor(int idProfe) {
            return base.Channel.EliminarProfesor(idProfe);
        }
        
        public System.Threading.Tasks.Task<bool> EliminarProfesorAsync(int idProfe) {
            return base.Channel.EliminarProfesorAsync(idProfe);
        }
        
        public bool InsertarProfesor(Cliente_WCF_Matriculas.ProxyProfesor.ProfesorDCINSERTS objProfesorDC) {
            return base.Channel.InsertarProfesor(objProfesorDC);
        }
        
        public System.Threading.Tasks.Task<bool> InsertarProfesorAsync(Cliente_WCF_Matriculas.ProxyProfesor.ProfesorDCINSERTS objProfesorDC) {
            return base.Channel.InsertarProfesorAsync(objProfesorDC);
        }
        
        public bool ActualizarProfesor(Cliente_WCF_Matriculas.ProxyProfesor.ProfesorDCUPDATES objProfesorDC) {
            return base.Channel.ActualizarProfesor(objProfesorDC);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarProfesorAsync(Cliente_WCF_Matriculas.ProxyProfesor.ProfesorDCUPDATES objProfesorDC) {
            return base.Channel.ActualizarProfesorAsync(objProfesorDC);
        }
    }
}
