//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SIS_MAT_MVC.ProxyConsultas {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuotaDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Matriculas")]
    [System.SerializableAttribute()]
    public partial class CuotaDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Est_cuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoCuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fecha_pagoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_alumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_cuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ndoc_cuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreCompletoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal Precio_cuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Tip_cuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TipoCuotaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime VencimientoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Est_cuota {
            get {
                return this.Est_cuotaField;
            }
            set {
                if ((this.Est_cuotaField.Equals(value) != true)) {
                    this.Est_cuotaField = value;
                    this.RaisePropertyChanged("Est_cuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EstadoCuota {
            get {
                return this.EstadoCuotaField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoCuotaField, value) != true)) {
                    this.EstadoCuotaField = value;
                    this.RaisePropertyChanged("EstadoCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fecha_pago {
            get {
                return this.Fecha_pagoField;
            }
            set {
                if ((this.Fecha_pagoField.Equals(value) != true)) {
                    this.Fecha_pagoField = value;
                    this.RaisePropertyChanged("Fecha_pago");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_alum {
            get {
                return this.Id_alumField;
            }
            set {
                if ((this.Id_alumField.Equals(value) != true)) {
                    this.Id_alumField = value;
                    this.RaisePropertyChanged("Id_alum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_cuota {
            get {
                return this.Id_cuotaField;
            }
            set {
                if ((this.Id_cuotaField.Equals(value) != true)) {
                    this.Id_cuotaField = value;
                    this.RaisePropertyChanged("Id_cuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ndoc_cuota {
            get {
                return this.Ndoc_cuotaField;
            }
            set {
                if ((object.ReferenceEquals(this.Ndoc_cuotaField, value) != true)) {
                    this.Ndoc_cuotaField = value;
                    this.RaisePropertyChanged("Ndoc_cuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompleto {
            get {
                return this.NombreCompletoField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreCompletoField, value) != true)) {
                    this.NombreCompletoField = value;
                    this.RaisePropertyChanged("NombreCompleto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Precio_cuota {
            get {
                return this.Precio_cuotaField;
            }
            set {
                if ((this.Precio_cuotaField.Equals(value) != true)) {
                    this.Precio_cuotaField = value;
                    this.RaisePropertyChanged("Precio_cuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Tip_cuota {
            get {
                return this.Tip_cuotaField;
            }
            set {
                if ((this.Tip_cuotaField.Equals(value) != true)) {
                    this.Tip_cuotaField = value;
                    this.RaisePropertyChanged("Tip_cuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoCuota {
            get {
                return this.TipoCuotaField;
            }
            set {
                if ((object.ReferenceEquals(this.TipoCuotaField, value) != true)) {
                    this.TipoCuotaField = value;
                    this.RaisePropertyChanged("TipoCuota");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Vencimiento {
            get {
                return this.VencimientoField;
            }
            set {
                if ((this.VencimientoField.Equals(value) != true)) {
                    this.VencimientoField = value;
                    this.RaisePropertyChanged("Vencimiento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MatriculadoDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Matriculas")]
    [System.SerializableAttribute()]
    public partial class MatriculadoDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Ape_AlumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DepartamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Des_semestreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dir_alumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DistritoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Dni_alumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Email_alumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_Ult_ModField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_nacField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime Fec_regField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_UbigeoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int Id_alumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_alumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nom_carreraField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProvinciaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tel_alumField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_RegistroField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Usu_Ult_ModField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ape_Alum {
            get {
                return this.Ape_AlumField;
            }
            set {
                if ((object.ReferenceEquals(this.Ape_AlumField, value) != true)) {
                    this.Ape_AlumField = value;
                    this.RaisePropertyChanged("Ape_Alum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento {
            get {
                return this.DepartamentoField;
            }
            set {
                if ((object.ReferenceEquals(this.DepartamentoField, value) != true)) {
                    this.DepartamentoField = value;
                    this.RaisePropertyChanged("Departamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Des_semestre {
            get {
                return this.Des_semestreField;
            }
            set {
                if ((object.ReferenceEquals(this.Des_semestreField, value) != true)) {
                    this.Des_semestreField = value;
                    this.RaisePropertyChanged("Des_semestre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dir_alum {
            get {
                return this.Dir_alumField;
            }
            set {
                if ((object.ReferenceEquals(this.Dir_alumField, value) != true)) {
                    this.Dir_alumField = value;
                    this.RaisePropertyChanged("Dir_alum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Distrito {
            get {
                return this.DistritoField;
            }
            set {
                if ((object.ReferenceEquals(this.DistritoField, value) != true)) {
                    this.DistritoField = value;
                    this.RaisePropertyChanged("Distrito");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni_alum {
            get {
                return this.Dni_alumField;
            }
            set {
                if ((object.ReferenceEquals(this.Dni_alumField, value) != true)) {
                    this.Dni_alumField = value;
                    this.RaisePropertyChanged("Dni_alum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email_alum {
            get {
                return this.Email_alumField;
            }
            set {
                if ((object.ReferenceEquals(this.Email_alumField, value) != true)) {
                    this.Email_alumField = value;
                    this.RaisePropertyChanged("Email_alum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_Ult_Mod {
            get {
                return this.Fec_Ult_ModField;
            }
            set {
                if ((this.Fec_Ult_ModField.Equals(value) != true)) {
                    this.Fec_Ult_ModField = value;
                    this.RaisePropertyChanged("Fec_Ult_Mod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_nac {
            get {
                return this.Fec_nacField;
            }
            set {
                if ((this.Fec_nacField.Equals(value) != true)) {
                    this.Fec_nacField = value;
                    this.RaisePropertyChanged("Fec_nac");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Fec_reg {
            get {
                return this.Fec_regField;
            }
            set {
                if ((this.Fec_regField.Equals(value) != true)) {
                    this.Fec_regField = value;
                    this.RaisePropertyChanged("Fec_reg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_Ubigeo {
            get {
                return this.Id_UbigeoField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_UbigeoField, value) != true)) {
                    this.Id_UbigeoField = value;
                    this.RaisePropertyChanged("Id_Ubigeo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id_alum {
            get {
                return this.Id_alumField;
            }
            set {
                if ((this.Id_alumField.Equals(value) != true)) {
                    this.Id_alumField = value;
                    this.RaisePropertyChanged("Id_alum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_alum {
            get {
                return this.Nom_alumField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_alumField, value) != true)) {
                    this.Nom_alumField = value;
                    this.RaisePropertyChanged("Nom_alum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nom_carrera {
            get {
                return this.Nom_carreraField;
            }
            set {
                if ((object.ReferenceEquals(this.Nom_carreraField, value) != true)) {
                    this.Nom_carreraField = value;
                    this.RaisePropertyChanged("Nom_carrera");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Provincia {
            get {
                return this.ProvinciaField;
            }
            set {
                if ((object.ReferenceEquals(this.ProvinciaField, value) != true)) {
                    this.ProvinciaField = value;
                    this.RaisePropertyChanged("Provincia");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tel_alum {
            get {
                return this.Tel_alumField;
            }
            set {
                if ((object.ReferenceEquals(this.Tel_alumField, value) != true)) {
                    this.Tel_alumField = value;
                    this.RaisePropertyChanged("Tel_alum");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Registro {
            get {
                return this.Usu_RegistroField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_RegistroField, value) != true)) {
                    this.Usu_RegistroField = value;
                    this.RaisePropertyChanged("Usu_Registro");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usu_Ult_Mod {
            get {
                return this.Usu_Ult_ModField;
            }
            set {
                if ((object.ReferenceEquals(this.Usu_Ult_ModField, value) != true)) {
                    this.Usu_Ult_ModField = value;
                    this.RaisePropertyChanged("Usu_Ult_Mod");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BloqueDC", Namespace="http://schemas.datacontract.org/2004/07/WCF_Matriculas")]
    [System.SerializableAttribute()]
    public partial class BloqueDC : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string HorarioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Id_bloqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Nombre_ProfesorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Tip_BloqueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short Total_matriculadosField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private short VacantesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((object.ReferenceEquals(this.EstadoField, value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Horario {
            get {
                return this.HorarioField;
            }
            set {
                if ((object.ReferenceEquals(this.HorarioField, value) != true)) {
                    this.HorarioField = value;
                    this.RaisePropertyChanged("Horario");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id_bloque {
            get {
                return this.Id_bloqueField;
            }
            set {
                if ((object.ReferenceEquals(this.Id_bloqueField, value) != true)) {
                    this.Id_bloqueField = value;
                    this.RaisePropertyChanged("Id_bloque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre_Profesor {
            get {
                return this.Nombre_ProfesorField;
            }
            set {
                if ((object.ReferenceEquals(this.Nombre_ProfesorField, value) != true)) {
                    this.Nombre_ProfesorField = value;
                    this.RaisePropertyChanged("Nombre_Profesor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tip_Bloque {
            get {
                return this.Tip_BloqueField;
            }
            set {
                if ((object.ReferenceEquals(this.Tip_BloqueField, value) != true)) {
                    this.Tip_BloqueField = value;
                    this.RaisePropertyChanged("Tip_Bloque");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Total_matriculados {
            get {
                return this.Total_matriculadosField;
            }
            set {
                if ((this.Total_matriculadosField.Equals(value) != true)) {
                    this.Total_matriculadosField = value;
                    this.RaisePropertyChanged("Total_matriculados");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Vacantes {
            get {
                return this.VacantesField;
            }
            set {
                if ((this.VacantesField.Equals(value) != true)) {
                    this.VacantesField = value;
                    this.RaisePropertyChanged("Vacantes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ProxyConsultas.IServicioConsultas")]
    public interface IServicioConsultas {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ListarCuotasPendientesAlumnos", ReplyAction="http://tempuri.org/IServicioConsultas/ListarCuotasPendientesAlumnosResponse")]
        SIS_MAT_MVC.ProxyConsultas.CuotaDC[] ListarCuotasPendientesAlumnos(int Id_Alum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ListarCuotasPendientesAlumnos", ReplyAction="http://tempuri.org/IServicioConsultas/ListarCuotasPendientesAlumnosResponse")]
        System.Threading.Tasks.Task<SIS_MAT_MVC.ProxyConsultas.CuotaDC[]> ListarCuotasPendientesAlumnosAsync(int Id_Alum);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ListarMatriculadosFechas", ReplyAction="http://tempuri.org/IServicioConsultas/ListarMatriculadosFechasResponse")]
        SIS_MAT_MVC.ProxyConsultas.MatriculadoDC[] ListarMatriculadosFechas(System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ListarMatriculadosFechas", ReplyAction="http://tempuri.org/IServicioConsultas/ListarMatriculadosFechasResponse")]
        System.Threading.Tasks.Task<SIS_MAT_MVC.ProxyConsultas.MatriculadoDC[]> ListarMatriculadosFechasAsync(System.DateTime fecIni, System.DateTime fecFin);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ListarAlumnosCarrera", ReplyAction="http://tempuri.org/IServicioConsultas/ListarAlumnosCarreraResponse")]
        SIS_MAT_MVC.ProxyConsultas.MatriculadoDC[] ListarAlumnosCarrera(int Id_carrera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ListarAlumnosCarrera", ReplyAction="http://tempuri.org/IServicioConsultas/ListarAlumnosCarreraResponse")]
        System.Threading.Tasks.Task<SIS_MAT_MVC.ProxyConsultas.MatriculadoDC[]> ListarAlumnosCarreraAsync(int Id_carrera);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ListarBloquesVacantes", ReplyAction="http://tempuri.org/IServicioConsultas/ListarBloquesVacantesResponse")]
        SIS_MAT_MVC.ProxyConsultas.BloqueDC[] ListarBloquesVacantes(short Vacantes);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicioConsultas/ListarBloquesVacantes", ReplyAction="http://tempuri.org/IServicioConsultas/ListarBloquesVacantesResponse")]
        System.Threading.Tasks.Task<SIS_MAT_MVC.ProxyConsultas.BloqueDC[]> ListarBloquesVacantesAsync(short Vacantes);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServicioConsultasChannel : SIS_MAT_MVC.ProxyConsultas.IServicioConsultas, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicioConsultasClient : System.ServiceModel.ClientBase<SIS_MAT_MVC.ProxyConsultas.IServicioConsultas>, SIS_MAT_MVC.ProxyConsultas.IServicioConsultas {
        
        public ServicioConsultasClient() {
        }
        
        public ServicioConsultasClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicioConsultasClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsultasClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicioConsultasClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SIS_MAT_MVC.ProxyConsultas.CuotaDC[] ListarCuotasPendientesAlumnos(int Id_Alum) {
            return base.Channel.ListarCuotasPendientesAlumnos(Id_Alum);
        }
        
        public System.Threading.Tasks.Task<SIS_MAT_MVC.ProxyConsultas.CuotaDC[]> ListarCuotasPendientesAlumnosAsync(int Id_Alum) {
            return base.Channel.ListarCuotasPendientesAlumnosAsync(Id_Alum);
        }
        
        public SIS_MAT_MVC.ProxyConsultas.MatriculadoDC[] ListarMatriculadosFechas(System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.ListarMatriculadosFechas(fecIni, fecFin);
        }
        
        public System.Threading.Tasks.Task<SIS_MAT_MVC.ProxyConsultas.MatriculadoDC[]> ListarMatriculadosFechasAsync(System.DateTime fecIni, System.DateTime fecFin) {
            return base.Channel.ListarMatriculadosFechasAsync(fecIni, fecFin);
        }
        
        public SIS_MAT_MVC.ProxyConsultas.MatriculadoDC[] ListarAlumnosCarrera(int Id_carrera) {
            return base.Channel.ListarAlumnosCarrera(Id_carrera);
        }
        
        public System.Threading.Tasks.Task<SIS_MAT_MVC.ProxyConsultas.MatriculadoDC[]> ListarAlumnosCarreraAsync(int Id_carrera) {
            return base.Channel.ListarAlumnosCarreraAsync(Id_carrera);
        }
        
        public SIS_MAT_MVC.ProxyConsultas.BloqueDC[] ListarBloquesVacantes(short Vacantes) {
            return base.Channel.ListarBloquesVacantes(Vacantes);
        }
        
        public System.Threading.Tasks.Task<SIS_MAT_MVC.ProxyConsultas.BloqueDC[]> ListarBloquesVacantesAsync(short Vacantes) {
            return base.Channel.ListarBloquesVacantesAsync(Vacantes);
        }
    }
}
